### PR TITLE
Fix person names to be case insensitive

### LINKED ISSUE #310: [PE-D][Tester A] Event commands require exact-case player names, making normal name entry unnecessarily brittle
## Description
Event-related commands only accept a player's name if the casing exactly matches the stored contact name.

## Steps to reproduce
1. Run `clear`
2. Run `add n/Alex Yeoh r/player p/91234567 e/alex@example.com a/1 Test Road tm/First Team st/Active pos/Forward`
3. Run `trainingadd n/Warm Up d/2026-05-15 1600 pl/alex yeoh`
4. Run `trainingadd n/Real Warm Up d/2026-05-15 1700 pl/Alex Yeoh`
5. Run `attendancemark 1 pl/alex yeoh`

## Expected
From a normal user perspective, entering the same player's name with different letter casing should still resolve to that player.

## Actual
- `trainingadd ... pl/alex yeoh` fails with `alex yeoh does not exist in the address book!`
- `attendancemark 1 pl/alex yeoh` fails with `This person does not exist in the address book!`

`trainingadd` failing:

Image

`attendancemark` failing:

Image

## Why this is a feature flaw
For a CLI-based roster manager, forcing users to remember exact casing makes normal event workflows less useful and more error-prone, especially since other name-based interactions such as `find` are already case-insensitive.

-------------
Labels: `severity.Low` `type.FeatureFlaw`

### PR DESCRIPTION
**Pull request by BarnabasSng**
Closes #310 and #234

Person names are now case insensitive. All commands which require person names should ignore casing

### CODE REVIEW

File: src/test/java/seedu/address/model/person/PersonTest.java [hunk 1]
```diff
@@ -44,7 +44,7 @@ public void isSamePerson() {
 
         // name differs in case, all other attributes same -> returns false
```
Comment (Arrus218) [inline src/test/java/seedu/address/model/person/PersonTest.java]: Just a nit here, comment should say returns true

File: src/main/java/seedu/address/model/person/Name.java [hunk 2]
```diff
@@ -56,7 +56,7 @@ public boolean equals(Object other) {
         }
 
         Name otherName = (Name) other;
-        return fullName.equals(otherName.fullName);
+        return fullName.equalsIgnoreCase(otherName.fullName);
```
Comment (Arrus218) [inline src/main/java/seedu/address/model/person/Name.java]: I think we should just trim the name to remove whitespaces as well

File: src/test/java/seedu/address/model/person/PersonTest.java
Comment (Arrus218) [inline src/test/java/seedu/address/model/person/PersonTest.java:48]: Can probably remove this part once change to trim name in Name.java `equals` method

**Review by Arrus218 — CHANGES_REQUESTED** [review]
LGTM other than some potential changes

**Review by Arrus218 — APPROVED** [review]
LGTM
