### PR TITLE
`set`/`update` integer overflow issues

### LINKED ISSUE #246: [PE-D][Tester B] Incorrect error given for set command
The user guide and command error does not highlight that there is a maximum integer that can be set and gives the impression that all positive integers are accepted.

Image

-------------
Labels: `severity.Low` `type.FunctionalityBug`

### PR DESCRIPTION
**Pull request by zenercurrent**
Fixes #246 #252 #276

Added more safeguards and clearer error messages for integer overflow problems
Also added disclaimer in UG on integer overflows

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/SetCommand.java [hunk 1]
```diff
@@ -31,6 +31,8 @@ public class SetCommand extends Command {
 
     public static final String MESSAGE_SET_PLAYER_SUCCESS = "Set %1$s\n%2$s: %3$s -> %4$s";
     public static final String MESSAGE_NOT_PLAYER = "This person must be a player.";
+    public static final String MESSAGE_STAT_OVERFLOW = "Set value has exceeded the maximum limit."
+            + "\nWhy are you trying to overflow it?";
```
Comment (DamianNgWZ) [inline src/main/java/seedu/address/logic/commands/SetCommand.java:35]: Might needa sound more professional here LOL.
Just keep to the first line

**Review by DamianNgWZ — APPROVED** [review]
LGTM other than an optional change
